---
- hosts: all
  sudo: yes
  vars:
    timezone: Europe/Amsterdam
  pre_tasks:
    - user: name=vagrant
  vars_files:
    - vars/php-fpm.yml
    - vars/typo3.yml
  roles:
    - role: common
      tags: "common"
    - role: php-fpm
      tags: 'php-fpm'
    - role: phpcommon
      tags: 'phpcommon'
    - role: hhvm
      tags: 'hhvm'
    - role: composer
      tags: 'composer'
    - role: nginx
      tags: 'nginx'
    - role: mariadb
      tags: 'mariadb'
    - role: typo3
      tags: 'typo3'
