---
- hosts: all
  sudo: yes
  gather_facts: yes
  vars:
    timezone: Europe/Amsterdam
  pre_tasks:
    - user: name=vagrant
  vars_files:
    - vars/php-fpm.yml
  roles:
    - role: common
      tags: "common"
    - role: php-fpm
      tags: 'php-fpm'
    - role: phpcommon
      tags: 'phpcommon'
    - role: hhvm
      tags: 'hhvm'
    - role: composer
      tags: 'composer'
    - role: nginx
      tags: 'nginx'
    - role: mariadb
      tags: 'mariadb'
