---
- hosts: all
  gather_facts: true
  sudo: yes
  vars_files:
    - Defaults/main.yml
    - Defaults/nginx.yml
    - Defaults/php.yml
    - Defaults/websites.yml
    - Defaults/typo3.yml
    - [ 'Configuration/main.yml' ,'Configuration/.keep' ]
    - [ 'Configuration/nginx.yml' ,'Configuration/.keep' ]
    - [ 'Configuration/php.yml' ,'Configuration/.keep' ]
    - [ 'Configuration/websites.yml' ,'Configuration/.keep' ]
    - [ 'Configuration/typo3.yml' ,'Configuration/.keep' ]
  roles:
    - { role: common,    tags: common }
    - { role: php-fpm,   tags: php-fpm }
    - { role: mariadb,   tags: mariadb }
    - { role: hhvm,      tags: hhvm }
    - { role: phpcommon, tags: phpcommon }
    - { role: composer,  tags: composer }
    - { role: typo3,     tags: typo3 }
    - { role: memcached, tags: memcached }
    - { role: nginx,     tags: nginx }
    - { role: nodejs,    tags: nodejs }
