---
- hosts: all
  gather_facts: true
  sudo: yes
  vars:
    timezone: Europe/Amsterdam
  vars_files:
    - vars/nginx.yml
    - vars/php-fpm.yml
    - vars/websites.yml
    - vars/typo3.yml
  roles:
    - { role: common,              tags: common }
    - { role: nbz4live.php-fpm,    tags: php-fpm }
    - { role: phpcommon,           tags: phpcommon }
    - { role: hhvm,                tags: hhvm }
    - { role: tersmitten.composer, tags: composer }
    - { role: mariadb,             tags: mariadb }
    - { role: typo3,               tags: typo3 }
# Waiting for the resolution of https://github.com/jdauphant/ansible-role-nginx/pull/33
#    - { role: jdauphant.nginx,     tags: nginx }
    - { role: nginx,     tags: nginx }
    - { role: laggyluke.nodejs,    tags: nodejs }
