---

- name: Clone TYPO3 CMS
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  git: repo={{ typo3_cms_src_repository }}
       dest={{ typo3_source_path }}/cms/typo3-cms

# Shallow clones do not contain remotely tracked branches
- name: Clone TYPO3 CMS Sources for tags
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  git: repo={{ typo3_source_path }}/cms/typo3-cms
       dest={{ typo3_source_path }}/cms/{{ item }}
       version={{ item }}
  with_items: typo3.cms.sources.tags
  tags: [typo3-cms-tags,tags]

- name: Clone TYPO3 CMS Sources for branches
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  git: repo={{ typo3_cms_src_repository }}
       dest={{ typo3_source_path }}/cms/{{ item }}
       version={{ item }}
  with_items: typo3.cms.sources.branches
  tags: [typo3-cms-branches,branches]

- name: Setup TYPO3 CMS site directories
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  file: path={{ typo3_webroot }}{{ item }} state=directory owner={{nginx_user}} group={{nginx_group}} mode=0775
  with_items: typo3.cms.sites.keys()
  tags: [typo3-cms-sites]

- name: Symlink TYPO3 CMS Sources into site roots
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  file: src={{ typo3_source_path }}/cms/{{ item.value }}
        dest={{ typo3_webroot }}{{ item.key }}/typo3_src state=link
  with_dict: typo3.cms.sites
  tags: [typo3-cms-symlink]

- name: Symlink to typo3 folder in site roots
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  file: src=typo3_src/typo3/
        dest={{ typo3_webroot }}{{ item.key }}/typo3 state=link
  with_dict: typo3.cms.sites
  tags: [typo3-cms-symlink]

- name: Symlink to t3lib folder in site roots
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  file: src=typo3_src/t3lib/
        dest={{ typo3_webroot }}{{ item.key }}/t3lib state=link
  when: item.key | match('^4\\.(5|6|7)\\.')
  with_dict: typo3.cms.sites
  tags: [typo3-cms-symlink]

- name: Symlink to typo3/index.php file in site roots
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  file: src=typo3_src/index.php
        dest={{ typo3_webroot }}{{ item.key }}/index.php state=link
  with_dict: typo3.cms.sites
  tags: [typo3-cms-symlink]

- name: Create fileadmin directories
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  file: path={{ typo3_webroot }}{{ item.key }}/fileadmin state=directory owner={{nginx_user}} group={{nginx_group}} mode=0775
  with_dict: typo3.cms.sites
  tags: [typo3-cms-directories]

- name: Create typo3conf directories
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  file: path={{ typo3_webroot }}{{ item.key }}/typo3conf state=directory owner={{nginx_user}} group={{nginx_group}} mode=0775
  with_dict: typo3.cms.sites
  tags: [typo3-cms-directories]

- name: Create typo3temp directories
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  file: path={{ typo3_webroot }}{{ item.key }}/typo3temp state=directory owner={{nginx_user}} group={{nginx_group}} mode=0775
  with_dict: typo3.cms.sites
  tags: [typo3-cms-directories]

- name: Create localconf.php
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  file: src=typo3_src/t3lib/
        path={{ typo3_webroot }}{{ item.key }}/typo3conf/localconf.php state=touch owner={{nginx_user}} group={{nginx_group}} mode=0664
  when: item.key | match('^4\\.(5|6|7)\\.')
  with_dict: typo3.cms.sites
  tags: [typo3-cms-localconf]

- name: Enable install tool
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  file: path={{ typo3_webroot }}{{ item.key }}/typo3conf/ENABLE_INSTALL_TOOL state=touch owner={{nginx_user}} group={{nginx_group}} mode=0664
  with_dict: typo3.cms.sites
  tags: [typo3-cms-installtool]

