---

- include_vars: default.yml
- include_vars: "{{ vhosts[vhost].download_from }}.yml"
- include_vars: default.yml
  tags:
    - data
    - files
- include_vars: "{{ vhosts[vhost].download_from }}.yml"
  tags:
    - files

- name: Creates directory
  file: path=/var/www/{{ vhost }}{{ vhosts[vhost].public_folder }}typo3temp state=directory
  tags:
    - data

- include: database.yml tags=database,data

- include: files.yml tags=files,data
