---

- name: Creates {{ typo3_source_path }}/cms directory
  file: path={{ typo3_source_path }}/cms state=directory owner={{ typo3.cms.sources.owner | default('vagrant') }} group={{ typo3.cms.sources.group | default('www-data') }} mode=0775

- name: Clone TYPO3 CMS
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  git: repo=git://git.typo3.org/Packages/TYPO3.CMS.git
       dest={{ typo3_source_path }}/cms/typo3-cms