---

# include the default vars and one of the environment var files
- include_vars: default.yml
- include_vars: "{{ vhosts[vhost].download_from }}.yml"
# include vars also when a tag is defined
- include_vars: default.yml
  tags:
    - data
    - git
    - vhostconfig
    - database
    - files
- include_vars: "{{ vhosts[vhost].download_from }}.yml"
  tags:
    - data
    - git
    - vhostconfig
    - database
    - files

- name: Checkout maxserv.com-cms6.git
  sudo: no
  action: git repo=ssh://git@stash.maxserv.com/max/maxserv.com-cms6.git dest=src/{{ vhost }} version=development
  tags:
    - data
    - git

- name: Creates directory
  file: path=/var/www/{{ vhost }}{{ vhosts[vhost].public_folder }}typo3temp state=directory
  tags:
    - data

- include: database.yml tags=database,data

- include: files.yml tags=files,data
