---

- name: Create base directories
  file: path={{ typo3_source_path }}/{{ item }} state=directory mode=0775
  with_items: typo3.keys()
  tags: [typo3-configuration]

- name: Make sure the nginx ssl directory extists
  file: path={{nginx_conf_dir}}/ssl state=directory owner=root group={{nginx_group}} mode=0755
  tags: [configuration,nginx,ssl]

- name: Generate ssl certificates for nginx sites (needs to run before nginx role)
  command: openssl req -x509 -sha512 -nodes -days 3650 -subj '/C=NL/ST=Noord-Brabant/O=MaxServ/L=Giessen/CN={{ item }}' -newkey rsa:4096 -keyout {{nginx_conf_dir}}/ssl/{{ item }}.key -out {{nginx_conf_dir}}/ssl/{{ item }}.crt creates={{nginx_conf_dir}}/ssl/{{ item }}.crt
  with_items: typo3_ssl_certificates
  notify:
    - reload nginx
  tags: [typo3-configuration,nginx,ssl]

- name: Setup push url to review.typo3.org
  sudo: "{{ typo3.cms.sources.owner | default('vagrant') }}"
  shell: git config --global url."ssh://{{ typo3_org_username }}@review.typo3.org:29418".pushInsteadOf git://git.typo3.org
  tags: [typo3-git-setup]

- include: defaultSite.yml
- include: mariadb.yml
- include: cms.yml
- include: cron.yml
- include: neos.yml