---

- name: Setup TYPO3 NEOS site directories
  sudo: "{{ typo3.neos.sources.owner | default('vagrant') }}"
  file: path={{ typo3_webroot }}{{ item }} state=directory mode=0775
  with_items: typo3.neos.sites.keys()
  tags: [typo3-neos-sites]
#
#- name: Setup TYPO3 NEOS sites
#  command: "composer create-project typo3/neos-base-distribution {{ typo3_webroot }}{{ item.key }}"
#  with_items: typo3.neos.sites
#  tags: [typo3-neos-sites]
