---

- name: Setup TYPO3 NEOS site directories
  sudo: "{{ typo3.neos.sources.owner | default('vagrant') }}"
  file: path={{ typo3_webroot }}{{ item }} state=directory mode=0775
  with_items: typo3.neos.sites.keys()
  tags: [typo3-neos-sites]

- name: Setup TYPO3 NEOS sites
  command: composer create-project typo3/neos-base-distribution {{ typo3_webroot }}{{ item.key }} {{ item.value }}
  with_dict: typo3.neos.sites
  tags: [typo3-neos-sites]

- name: Create ramdisk directories to offload Data/Temporary to ramdisk
  file: path=/mnt/typo3cache/{{ item }} state=directory owner={{nginx_user}} group={{nginx_group}} mode=0775
  with_items: typo3.neos.sites.keys()
  tags: [typo3-neos-ramdisk]

- name: Make fstab entries for TYPO3 NEOS Data/Temporary
  mount: src=/mnt/typo3cache/{{ item }} name={{ typo3_webroot }}{{ item }}/Data/Temporary/ fstype=none opts=bind,noauto state=present
  with_items: typo3.neos.sites.keys()
  tags: [typo3-neos-ramdisk]

- name: Mount bind TYPO3 NEOS Data/Temporary ramdisks
  command: mount /mnt/typo3cache/{{ item }}
  with_items: typo3.neos.sites.keys()
  tags: [typo3-neos-ramdisk]
