---

- name: Setup TYPO3 NEOS site directories
  sudo: "{{ typo3.neos.sources.owner | default('vagrant') }}"
  file: path={{ typo3_webroot }}{{ item }} state=directory owner={{nginx_user}} group={{nginx_group}} mode=0775
  with_items: typo3.neos.sites.keys()
  tags: [typo3-neos-sites]
