---
php_ini_path: /etc/php5/fpm/php.ini
php_cli_ini_path: /etc/php5/cli/php.ini
php_apc_ini_path: /etc/php5/mods-available/apcu.ini
php_xdebug_ini_path: /etc/php5/mods-available/xdebug.ini
php_common_ppa: php5
php_common_enable_blackfire: yes
php_common_packages:
    - 'php-pear'
    - 'php5-apcu'
    - 'php5-cli'
    - 'php5-curl'
    - 'php5-gd'
    - 'php5-gmp'
    - 'php5-json'
    - 'php5-mcrypt'
    - 'php5-memcache'
    - 'php5-mysqlnd'
    - 'php5-pgsql'
    - 'php5-redis'
    - 'php5-sqlite'
    - 'php5-xdebug'
    - 'php5-xhprof'