---
- name: Creates directory
  sudo: no
  local_action: file path=sql state=directory

#database import
- name: setup empty database for typo3
  mysql_db: name={{ vhosts[vhost].database }} encoding=utf8 collation=utf8_general_ci state=present login_user=root login_password={{ mysql_root_pwd }}
- name: setup MySQL user for typo3
  mysql_user: name={{ vhosts[vhost].database }} password=sowdipf host=localhost priv={{ vhosts[vhost].database }}.*:ALL state=present
- name: download database schema
  when: vhosts[vhost].downloaddb
  sudo: no
  local_action: shell ssh {{ remote_ssh.user }}@{{ remote_ssh.host}}
      "mysqldump -d -h {{ remote_db.host }} -u {{ remote_db.user }} -p{{ remote_db.password }} {{ remote_db.name }}" > sql/{{ vhost }}-schema.sql
- name: download database
  when: vhosts[vhost].downloaddb
  sudo: no
  local_action: shell ssh {{ remote_ssh.user }}@{{ remote_ssh.host}} "mysqldump --skip-lock-tables --skip-add-drop-table --no-create-info
      --ignore-table={{ remote_db.name }}.be_sessions
      --ignore-table={{ remote_db.name }}.cache_extensions
      --ignore-table={{ remote_db.name }}.cache_hash
      --ignore-table={{ remote_db.name }}.cache_imagesizes
      --ignore-table={{ remote_db.name }}.cache_md5params
      --ignore-table={{ remote_db.name }}.cache_pages
      --ignore-table={{ remote_db.name }}.cache_pagesection
      --ignore-table={{ remote_db.name }}.cache_typo3temp_log
      --ignore-table={{ remote_db.name }}.cf_cache_hash
      --ignore-table={{ remote_db.name }}.cf_cache_hash_tags
      --ignore_table={{ remote_db.name }}.cf_cache_pagesection
      --ignore-table={{ remote_db.name }}.fe_session_data
      --ignore-table={{ remote_db.name }}.index_rel
      --ignore-table={{ remote_db.name }}.index_fulltext
      --ignore-table={{ remote_db.name }}.index_phash
      --ignore-table={{ remote_db.name }}.index_words
      --ignore-table={{ remote_db.name }}.index_section
      --ignore-table={{ remote_db.name }}.sys_history
      --ignore-table={{ remote_db.name }}.sys_log
      --ignore-table={{ remote_db.name }}.tt_news_cache
      --ignore-table={{ remote_db.name }}.tx_dam_log_index
      --ignore-table={{ remote_db.name }}.tx_devlog
      --ignore-table={{ remote_db.name }}.tx_extbase_cache_reflection
      --ignore-table={{ remote_db.name }}.tx_realurl_chashcache
      --ignore-table={{ remote_db.name }}.tx_realurl_errorlog
      --ignore-table={{ remote_db.name }}.tx_realurl_uniqalias
      --ignore-table={{ remote_db.name }}.tx_realurl_decodecache
      --ignore-table={{ remote_db.name }}.tx_realurl_urlencodecache
      --ignore-table={{ remote_db.name }}.tx_dam_log_index
      -h {{ remote_db.host }} -u {{ remote_db.user }} -p{{ remote_db.password }} {{ remote_db.name }}" > sql/{{ vhost }}-data.sql
- name: copy sql schema
  when: vhosts[vhost].downloaddb
  copy: src=sql/{{ vhost }}-schema.sql dest=/tmp/{{ vhost }}-schema.sql
- name: copy sql data
  when: vhosts[vhost].downloaddb
  copy: src=sql/{{ vhost }}-data.sql dest=/tmp/{{ vhost }}-data.sql
- name: copy sql domain fix
  when: vhosts[vhost].downloaddb
  template: src=domainfix.sql.j2 dest=/tmp/{{ vhost }}-domainfix.sql
- name: import typo3 database schema
  when: vhosts[vhost].downloaddb
  mysql_db: name={{ vhosts[vhost].database }} state=import target=/tmp/{{ vhost }}-schema.sql
- name: import typo3 data
  when: vhosts[vhost].downloaddb
  mysql_db: name={{ vhosts[vhost].database }} state=import target=/tmp/{{ vhost }}-data.sql
- name: change domain to {{ vhost }}
  when: vhosts[vhost].downloaddb
  mysql_db: name={{ vhosts[vhost].database }} state=import target=/tmp/{{ vhost }}-domainfix.sql