---

- name: Add PackageCloud repo key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: Add PackageCloud repo
  shell: echo deb http://packages.blackfire.io/debian any main | sudo tee /etc/apt/sources.list.d/blackfire.list

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install Blackfire
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: [ blackfire-agent, blackfire-php ]

- name: Disable remote xdebug
  file: src=../../mods-available/xdebug.ini dest=/etc/php5/fpm/conf.d/20-xdebug.ini state=absent force=yes
  notify:
    - restart php-fpm
  tags: [ configuration, php, xdebug ]

- name: Disable xhprof
  file: src=../../mods-available/xhprof.ini dest=/etc/php5/fpm/conf.d/20-xhprof.ini state=absent force=yes
  notify:
    - restart php-fpm
  tags: [ configuration, php, xhprof ]
