---

- name: Add OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [ test, php-apcu, php-opcache, php-xdebug, php-blackfire ]

- name: Phpbrew install build dependancies
  command: apt-get build-dep -y php5

- name: Phpbrew install required packages
  apt: name={{ item }} state=present
  with_items: php_brew_required_packages

- name: Phpbrew prevent freetype.h not found configure error
  shell: mkdir /usr/include/freetype2/freetype; ln -s /usr/include/freetype2/freetype.h /usr/include/freetype2/freetype/freetype.h

- name: Phpbrew install
  get_url: url=https://github.com/phpbrew/phpbrew/raw/master/phpbrew dest=/usr/bin/phpbrew mode=0755
  tags: test

- name: Phpbrew init
  command: phpbrew init
  tags: test

- name: Phpbrew set lookup prefix
  command: phpbrew lookup-prefix ubuntu
  tags: test

#phpbrew install 5.3.29 +default+fpm+mysql+fileinfo+gd+intl+mcrypt+mhash+openssl+pcre+session+soap+zlib

- name: Customize PHP fpm configuration file
  ini_file: dest={{ php_fpm_ini_path }} section="{{ item.section }}" option="{{ item.option }}" value="{{ item.value }}" backup=yes
  with_items: php_ini
  notify:
   - restart php-fpm

- name: Customize PHP cli configuration file
  ini_file: dest={{ php_cli_ini_path }} section="{{ item.section }}" option="{{ item.option }}" value="{{ item.value }}" backup=yes
  with_items: php_ini

- include: apcu.yml
  tags: php-apcu

- include: blackfire.yml
  tags: php-blackfire

- include: opcache.yml
  tags: php-opcache

- include: xdebug.yml
  tags: php-xdebug

- name: Enable php modules
  command: php5enmod {{ item }}
  with_items: php_enabled_modules
  notify:
    - restart php-fpm

- name: Disable php modules
  command: php5dismod {{ item }}
  with_items: php_disabled_modules
  notify:
    - restart php-fpm
