---

- name: Phpbrew install build dependancies
  command: apt-get build-dep -y php5

- name: Phpbrew install required packages
  apt: name={{ item }} state=present
  with_items: php_brew_required_packages

- name: Check if freetype symlink exists
  stat: path=/usr/include/freetype2/freetype/freetype.h
  register: freetype_link_check

- name: Phpbrew prevent freetype.h not found configure error
  shell: mkdir /usr/include/freetype2/freetype; ln -s /usr/include/freetype2/freetype.h /usr/include/freetype2/freetype/freetype.h
  when: not freetype_link_check.stat.exists

- name: Phpbrew install
  get_url: url=https://github.com/phpbrew/phpbrew/raw/master/phpbrew dest=/usr/bin/phpbrew mode=0755

- name: Phpbrew init
  command: phpbrew init

- name: Phpbrew profile setup
  shell: echo '# phpbrew setup' > /etc/profile.d/phpbrew.sh; echo 'export PHPBREW_ROOT=/usr/local/phpbrew' >> /etc/profile.d/phpbrew.sh; echo 'export PHPBREW_SET_PROMPT=1' >> /etc/profile.d/phpbrew.sh; echo 'source ~/.phpbrew/bashrc' >> /etc/profile.d/phpbrew.sh; executable=/bin/bash

- name: Brew php versions
  shell: if [ ! -f /usr/local/phpbrew/php/php-{{ item }}/bin/php ]; then phpbrew install {{ item }} {{ php_brew_options }}; fi
  environment:
    PHPBREW_ROOT: /usr/local/phpbrew
  with_items: php_brew_versions

- name: Customize PHP brew configuration files
  ini_file: dest=/usr/local/phpbrew/php/php-{{ item[0] }}/etc/php.ini section="{{ item[1].section }}" option="{{ item[1].option }}" value="{{ item[1].value }}" backup=yes
  with_nested:
    - php_brew_versions
    - php_ini

- name: Copy default FPM configuration file
  template: dest=/usr/local/phpbrew/php/php-{{ item }}/etc src=php-fpm.conf.j2
  with_items: php_brew_versions

- name: Copy the FPM configuration
  ini_file: >
    dest=/usr/local/phpbrew/php/php-{{ item[0] }}/etc/php-fpm.conf
    section="{{ item[1].section }}"
    option="{{ item[1].option }}"
    value="{{ item[1].value }}"
    backup=yes
  with_nested:
    - php_brew_versions
    - php_fpm_config

- name: Setup pool.d directories
  file: path=/usr/local/phpbrew/php/php-{{ item }}/etc/pool.d state=directory mode=0775
  with_items: php_brew_versions

- name: Delete the default POOL configuration file
  file: >
    path=/usr/local/phpbrew/php/php-{{ item[0] }}/etc/pool.d/{{ php_fpm_default_pool.name }}
    state=absent
  with_items: php_brew_versions
  when: php_fpm_default_pool.delete

- name: Copy the POOL configurations
  template: >
    src=pool.conf.j2
    dest=/usr/local/phpbrew/php/php-{{ item[0] }}/etc/pool.d/{{ item[1]['name'] }}.conf
    backup=yes
  with_nested:
    - php_brew_versions
    - php_fpm_pools
  when: php_fpm_pools|lower != 'none'

- name: Set correct listening sockets
  lineinfile: >
    dest=/usr/local/phpbrew/php/php-{{ item[0] }}/etc/pool.d/{{ item[1]['name'] }}.conf
    regexp="^\s*listen\s*=\s/var/run/php5-fpm(.{{ item[1]['name'] }})?.sock"
    line="listen = /var/run/php-fpm.{{ item[0] }}.{{ item[1]['name'] }}.sock"
    backrefs=yes
  with_nested:
    - php_brew_versions
    - php_fpm_pools

#https://github.com/phpbrew/phpbrew
#https://github.com/phpbrew/phpbrew/wiki