---

- name: Disable atime on root filesystem
  mount: name=/ src=/dev/sda1 fstype=ext4 opts=rw,noatime state=mounted

- name: Update apt package lists
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: "{{ homestead.cache_valid_time }}"
  when: homestead.update_cache

- name: Upgrade all packages
  apt: upgrade=dist
  when: homestead.upgrade_packages

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Autoremove unused packages
  command: apt-get -y autoremove --purge

- name: Install Some PPAs - software-properties-common
  apt: name=software-properties-common state=present

- name: Add package repositories
  apt_repository: repo={{ item }}
  with_items:
    - "ppa:nginx/stable"
    - "ppa:rwky/redis"
    - "ppa:chris-lea/node.js"

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install Extra Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: sys_packages

- name: Put vagrant user in www-data group
  user: name=vagrant groups=www-data append=yes

- name: Configure the timezone
  sudo: yes
  template: src=timezone.tpl.j2 dest=/etc/timezone

- name: More Configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set the hostname in /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ hostname }}' owner=root group=root mode=0644
  when: hostname is defined

- name: Setup dircolors
  sudo: vagrant
  copy: src=dircolors dest=~/.dircolors force=no

- name: Setup postfix as a null mailer
  sudo: yes
  copy: src=postfix_main.cf dest=/etc/postfix/main.cf force=no

- name: Start the postfix service
  service: name=postfix state=started enabled=yes
  tags: [service,postfix]

- name: Make fstab entry for TYPO3 ramdisk
  mount: name=/var/lib/php5/sessions src=tmpfs fstype=tmpfs opts='atime,nosuid,nodev,size=10m' state=mounted
  tags: test

- include: ramdisk.yml
  tags: ramdisk

- include: ssh.yml
  tags: ssh

- include: zsh.yml
  when: homestead.use_zsh
  tags: zsh
