---

- name: Make fstab entry for php sessions ramdisk
  mount: name=/var/lib/php5 src=tmpfs fstype=tmpfs opts='atime,nosuid,nodev,size=10m' state=mounted

- name: Create mountpoint for TYPO3 ramdisk
  file: path=/mnt/typo3cache state=directory owner=vagrant group={{nginx_group}} mode=0755

- name: Make fstab entry for TYPO3 ramdisk
  mount: name=/mnt/typo3cache src=tmpfs fstype=tmpfs opts='noatime,nosuid,nodev,size=256m' state=mounted

- name: Set recursive ACL for TYPO3 ramdisk
  command: setfacl -m g:{{nginx_group}}:rwX,d:g:{{nginx_group}}:rwX,g:vagrant:rwX,d:g:vagrant:rwX /mnt/typo3cache
