---

- name: Add authorized keys from host user
  authorized_key: >
    user=vagrant
    key="{{ lookup('file', item) }}"
    state=present
  with_items: homestead_ssh_public_keys
  tags: ssh-keys

- name: Get host keys
  shell: ssh-keyscan {{ item }}
  with_items: homestead_ssh_known_hosts
  register: ssh_keyscan_results
  tags: ssh-keys

- name: Add the public keys if needed
  lineinfile: create=yes dest=/etc/ssh/ssh_known_hosts line='{{ item.stdout }}' state=present
  with_items: ssh_keyscan_results.results
  tags: ssh-keys
